### ISSUE TITLE
Failing to construct client socket kills app completely

### ISSUE THREAD

**Issue by jamestomasino** [kensanata/moku-pona#2]
`Cannot construct client socket to alexschroeder.ch:70: Network is unreachable`

This is killing moku-pona update completely rather than timing-out and continuing onto the next phlog in the list.

**Comment by kensanata** [comment]
Hm, do you have a merge request I could merge from a mobile device? I’m currently traveling and might not have the time to look into this.

**Comment by kensanata** [comment]
Fixed by 280fecc. Please reopen if this is not enough.
