### ISSUE TITLE
Duplicated listings

### ISSUE THREAD

**Issue by jamestomasino** [kensanata/moku-pona#3]
Recently some phlog listings have begun duplicating when their phlogs update. I'm not 100% sure, but it looks like it's happening on individuals that have multiple phlogs on different servers. Maybe it's because there's more than one shared string in them, or maybe it's because I'm indicating server by adding paranthetical labels (sdf.org) (circumlunar.space).

You can see it here:
gopher://gopher.black/1/moku-pona/

tfurrows and yargo are the curent culprits.

**Comment by kensanata** [comment]
Hm, could be because I don’t escape meta characters and the parenthesis are treated like special characters in a regular expression. Must check that.

**Comment by jamestomasino** [comment]
I changed parenthesis to dashes and the problem goes away. It does indeed look to be related to escaping of special characters.

**Comment by kensanata** [comment]
I've been trying to reproduce the problem and was unable to do it. I did stuff like `moku-pona add alexschroeder.ch "alex (1)"` and `moku-pona add alexschroeder.ch "alex (2)" and variations thereof. Please reopen if this is still a problem.
